#!/usr/bin/env bun
/**
 * JournalEntry.ts - Trade Journal Entry Creator
 *
 * Creates structured markdown journal entries for trades.
 * Saves to data/journal/YYYY-MM/ directory.
 *
 * Usage:
 *   bun JournalEntry.ts --ticker AAPL --direction long --entry 185.50 --exit 192.30 --size 100 --thesis "earnings momentum"
 *   bun JournalEntry.ts --ticker AAPL --direction short --entry 185.50 --size 100 --thesis "overbought" --stop-loss 188.00
 */

import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { join, resolve, dirname } from 'path';

// Parse command line arguments
function parseArgs(argv: string[]): Record<string, string | boolean> {
  const args: Record<string, string | boolean> = {};
  for (let i = 2; i < argv.length; i++) {
    if (argv[i].startsWith('--')) {
      const key = argv[i].slice(2);
      const nextValue = argv[i + 1];
      if (nextValue && !nextValue.startsWith('--')) {
        args[key] = nextValue;
        i++;
      } else {
        args[key] = true;
      }
    }
  }
  return args;
}

const PROJECT_ROOT = resolve(dirname(new URL(import.meta.url).pathname), '../..');

// Calculate P&L
function calculatePL(
  entry: number,
  exit: number | null,
  size: number,
  direction: 'long' | 'short'
): { dollarPL: string; percentPL: string } {
  if (!exit) {
    return { dollarPL: 'N/A', percentPL: 'N/A' };
  }

  const dollarChange = direction === 'long' ? (exit - entry) : (entry - exit);
  const dollarPL = dollarChange * size;
  const percentPL = (dollarChange / entry) * 100;

  return {
    dollarPL: `$${dollarPL.toFixed(2)}`,
    percentPL: `${percentPL.toFixed(1)}%`,
  };
}

// Calculate duration
function calculateDuration(entryDate: Date, exitDate: Date | null): string {
  if (!exitDate) {
    const now = new Date();
    const days = Math.floor((now.getTime() - entryDate.getTime()) / (1000 * 60 * 60 * 24));
    return `${days} days (open)`;
  }

  const days = Math.floor((exitDate.getTime() - entryDate.getTime()) / (1000 * 60 * 60 * 24));
  return `${days} days`;
}

// Generate journal entry markdown
function generateJournalEntry(params: {
  ticker: string;
  direction: 'long' | 'short';
  entry: number;
  exit: number | null;
  size: number;
  thesis: string;
  stopLoss?: string;
  target?: string;
  notes?: string;
  date: Date;
}): string {
  const { ticker, direction, entry, exit, size, thesis, stopLoss, target, notes, date } = params;

  const dateStr = date.toISOString().split('T')[0];
  const pl = calculatePL(entry, exit, size, direction);
  const duration = calculateDuration(date, exit ? new Date() : null);

  const directionLabel = direction.charAt(0).toUpperCase() + direction.slice(1);
  const exitStr = exit ? `$${exit.toFixed(2)}` : 'Open';

  return `# Trade Journal: ${ticker} ${directionLabel}

- **Date:** ${dateStr}
- **Ticker:** ${ticker}
- **Direction:** ${directionLabel}
- **Entry:** $${entry.toFixed(2)}
- **Exit:** ${exitStr}
- **Size:** ${size} shares
- **P&L:** ${pl.dollarPL} (${pl.percentPL})
- **Duration:** ${duration}
- **Thesis:** ${thesis}${stopLoss ? `\n- **Stop Loss:** $${stopLoss}` : ''}${target ? `\n- **Target:** $${target}` : ''}

## Setup

What was the signal/setup that triggered this trade?

${notes || '[Add notes about the setup, technical patterns, catalyst, etc.]'}

## Execution

How did the entry/exit go? Any slippage or issues?

[Add notes about order execution, fills, etc.]

## Outcome

What happened after entry? Did the trade play out as expected?

${exit ? '[Describe how the trade played out and why you exited]' : '[Trade is still open]'}

## Reflection

- **What went right:**
- **What went wrong:**
- **Would take again:** Yes / No / Maybe
- **Key learning:**

## Tags

#trading #${ticker.toLowerCase()} #${direction} ${exit ? (pl.dollarPL.startsWith('-') ? '#loss' : '#win') : '#open'}

---

*Generated by Harvest Trading Pipeline*
`;
}

// Show help
function showHelp() {
  console.log(`
Trade Journal Entry Creator

Usage:
  bun JournalEntry.ts [options]

Required Options:
  --ticker <symbol>         Stock ticker symbol
  --direction <long|short>  Trade direction
  --entry <price>           Entry price
  --size <shares>           Number of shares
  --thesis <text>           Trade thesis/reason

Optional Options:
  --exit <price>         Exit price (omit if still open)
  --stop-loss <price>    Stop loss price
  --target <price>       Target price
  --notes <text>         Additional notes
  --help                 Show this help message

Examples:
  # Closed long trade
  bun JournalEntry.ts --ticker AAPL --direction long --entry 185.50 --exit 192.30 --size 100 --thesis "earnings momentum"

  # Open short trade with stop loss
  bun JournalEntry.ts --ticker TSLA --direction short --entry 350.00 --size 50 --thesis "overbought RSI" --stop-loss 360.00 --target 320.00

Output:
  Creates markdown file at:
  data/journal/YYYY-MM/YYYY-MM-DD-TICKER-DIRECTION.md
`);
}

// Main execution
async function main() {
  const args = parseArgs(process.argv);

  if (args.help) {
    showHelp();
    process.exit(0);
  }

  // Validate required arguments
  const required = ['ticker', 'direction', 'entry', 'size', 'thesis'];
  for (const field of required) {
    if (!args[field]) {
      console.error(`Error: --${field} is required`);
      showHelp();
      process.exit(1);
    }
  }

  const ticker = (args.ticker as string).toUpperCase();
  const direction = (args.direction as string).toLowerCase();

  if (direction !== 'long' && direction !== 'short') {
    console.error('Error: --direction must be "long" or "short"');
    process.exit(1);
  }

  const entry = parseFloat(args.entry as string);
  const exit = args.exit ? parseFloat(args.exit as string) : null;
  const size = parseInt(args.size as string, 10);
  const thesis = args.thesis as string;

  if (isNaN(entry) || isNaN(size)) {
    console.error('Error: --entry and --size must be valid numbers');
    process.exit(1);
  }

  if (exit !== null && isNaN(exit)) {
    console.error('Error: --exit must be a valid number');
    process.exit(1);
  }

  const now = new Date();
  const yearMonth = now.toISOString().slice(0, 7); // YYYY-MM
  const dateStr = now.toISOString().split('T')[0]; // YYYY-MM-DD

  // Generate journal entry
  const journalContent = generateJournalEntry({
    ticker,
    direction: direction as 'long' | 'short',
    entry,
    exit,
    size,
    thesis,
    stopLoss: args['stop-loss'] as string | undefined,
    target: args.target as string | undefined,
    notes: args.notes as string | undefined,
    date: now,
  });

  // Create output directory
  const journalDir = join(PROJECT_ROOT, 'data', 'journal', yearMonth);

  if (!existsSync(journalDir)) {
    mkdirSync(journalDir, { recursive: true });
  }

  // Write journal entry
  const filename = `${dateStr}-${ticker}-${direction}.md`;
  const filepath = join(journalDir, filename);

  writeFileSync(filepath, journalContent, 'utf-8');

  console.log(JSON.stringify({
    success: true,
    filepath,
    ticker,
    direction,
    entry,
    exit: exit || 'open',
    size,
  }, null, 2));

  process.exit(0);
}

main();
